services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      - API_URL=https://api.xyai.xin
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DOMAIN=api.xyai.xin
    env_file:
      - .env
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/certs:/etc/nginx/certs # 挂载证书
    depends_on:
      - frontend
      - backend
