services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    command: []
    volumes:
      - ./frontend:/app
      - ./frontend-dist:/frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DOMAIN=api.xyai.xin

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /root/certs:/etc/nginx/certs:ro       # 挂载外部证书目录
      - ./frontend-dist:/frontend:ro         # 挂载前端构建文件
    depends_on:
      - frontend
      - backend

  acme:
    image: neilpang/acme.sh
    container_name: acme
    command: daemon
    volumes:
      - /root/certs:/certs                   # 证书存储在项目外部
      - ~/.acme.sh:/acme.sh
    environment:
      - ACME_HOME=/acme.sh
