services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - ./frontend-dist:/frontend-dist  # 输出静态文件

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"  # 后端服务端口
    environment:
      - DOMAIN=api.xyai.xin

  frontend-nginx:
    image: nginx:latest
    container_name: frontend-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"  # SSL 支持
    volumes:
      - ./nginx/frontend-nginx.conf:/etc/nginx/nginx.conf
      - ./frontend-dist:/frontend:ro  # 挂载前端静态文件
      - ~/certs:/etc/nginx/certs:ro  # SSL 证书
    depends_on:
      - frontend

  backend-nginx:
    image: nginx:latest
    container_name: backend-nginx
    restart: always
    ports:
      - "8001:80"
      - "8443:443"  # 后端服务监听的 HTTPS 端口
    volumes:
      - ./nginx/backend-nginx.conf:/etc/nginx/nginx.conf
      - ~/certs:/etc/nginx/certs:ro  # SSL 证书
    depends_on:
      - backend
