services:
  frontend:
    image: node:23.5-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      sh -c "pnpm install && pnpm build"
    environment:
      - NODE_ENV=production
    build:
      context: ./frontend
    ports:
      - "3000:3000" # 开发时访问端口
    depends_on:
      - backend

  backend:
    image: python:3.13.1-alpine
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: >
      sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /root/certs:/etc/nginx/certs # 挂载证书
      - ./frontend/dist:/usr/share/nginx/html # 静态文件
    depends_on:
      - frontend
      - backend
