services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    networks:
      - app-network
    restart: always
#    volumes:
#      - ./frontend/dist:/frontend/dist

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
#      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: always

  acme:
    image: neilpang/acme.sh
    container_name: acme.sh
    entrypoint: "/bin/sh -c"
    environment:
      - ALI_Key=${ALI_KEY}
      - ALI_Secret=${ALI_SECRET}
    command: |
      "acme.sh --issue --dns dns_ali -d xyai.xin -d api.xyai.xin
      && cp /root/.acme.sh/xyai.xin/* /etc/nginx/certs/
      && nginx -s reload"
    volumes:
      - ./certs:/etc/nginx/certs
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
