services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
#    volumes:
#      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    container_name: backend
#    working_dir: /app
#    volumes:
#      - ./backend:/app
    environment:
      - DOMAIN=api.xyai.xin
    restart: always
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/frontend-nginx.conf:/etc/nginx/conf.d/frontend-nginx.conf
      - ./nginx/backend-nginx.conf:/etc/nginx/conf.d/backend-nginx.conf
      - /root/certs:/etc/nginx/certs # 挂载证书
      - ./frontend/dist:/usr/share/nginx/html # 静态文件
    depends_on:
      - frontend
      - backend
