name: Deploy to Server

on:
  push:
    branches:
      - master # 当代码推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. 设置 SSH 密钥
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    # 3. 部署代码到服务器
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@8.218.251.198 "
        cd /root/wwwroot/xy-ai &&
        git pull origin master &&
        docker compose down &&
        docker compose up -d --build
        "
